services:
  - type: web
    name: project-genesis-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    branch: main
    rootDir: backend
